### ISSUE TITLE
SQL SAVE command does not work on unix file systems

### ISSUE THREAD

**Issue by acediac** [andrewtacon/DigitalSolutionsNotebook#1]
When executing the SAVE command in SQL the full filepath contains a hardcoded backslash which creates an incorrect path on Mac / Unix filesystems.

I believe in the file /src/extension/extension.ts, the hardcoded backslash path on line 50 needs to be changed to  something like ${pathSeparator} so that it will work on unix-style systems.

**Comment by andrewtacon** [comment]
I had a look. The ${pathSeparator} is part of the json config files (I think).

I have changed the separator in that particular line to be '/' as opposed to a  double '\\'.

I can only test on windows so I have no idea if this works on Mac/Unix.

This update just rolled out as v 0.2.0

**Comment by acediac** [comment]
Ok, I'm not really familiar with vscode extensions. You did the same fix as what I did as a temporary fix locally on mine, I just didn't think it would work on Windows. I've just tested v0.2.0 and the sql command "SAVE filename.db" works properly on macOS now (presumably on unix also). Thanks.
